language: python
dist: xenial

os:
  - linux   # TODO: Migrate to a different CI service because Travis does not natively support Python on OSX or Windows.

python:
  - '3.7-dev'     # TODO: Replace with plain "3.7" when supported by Travis
#  - '3.8-dev'    # TODO: Compatibility issues with MyPy, see https://travis-ci.org/UAVCAN/pydsdl/jobs/519988157

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls  # Intentionally removed from requirements.txt because it's only useful in the CI environment

script:
  - ./test.sh
  - coveralls  # Publish the coverage stats online.
