environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"

stack: python %PYTHON%

install:
  - git submodule update --init --recursive
  - python -V
  - pip install coveralls               # Removed from requirements.txt because it's only useful on the CI.

  # GNU/Linux build config
  - sh: "sudo apt-get install graphviz -y"

  # Windows build config
  - cmd: "SET PATH=%PYTHON%;%PATH%"
  - cmd: "SET PATH=C:\\Python37-x64\\Scripts;%PATH%"

build: off

test_script:
  - sh: "./test.sh"
  - sh: "echo 'TODO: run SonarQube'"

after_test:
  - coveralls
