environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python38-x64'
      PYTHON_ARCH: '64'

# Python 3.9 is temporarily disabled because NumPy fails to import with this error:
# ImportError: /home/appveyor/venv3.9.0/lib/python3.9/site-packages/numpy/random/mtrand.cpython-39-x86_64-linux-gnu.so:
#              undefined symbol: PyCMethod_New
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
#      PYTHON: '3.9'

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: '3.8'
      coverage: 1    # The coverage information shall be published from exactly one job.

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: '3.7'

stack: python %PYTHON%

build: off

install:
  - git submodule update --init --recursive

  # GNU/Linux build config
  - sh: 'lsb_release -a'
  - sh: 'export extras_pkg="linux-*-extra-$(uname -r)"'
  - sh: 'echo $extras_pkg'
  - sh: 'sudo apt-get install -y $extras_pkg graphviz ncat'

  # MS Windows build config
  - cmd: 'systeminfo'
  - cmd: 'set PATH=%PYTHON%;%PATH%'
  - cmd: 'set PATH=C:\\Python38-x64\\Scripts;%PATH%'

  # Config check
  - 'python -V'

test_script:
  # GNU/Linux test
  - sh: './test.sh'

  # MS Windows test
  - cmd: 'powershell .\test.ps1'

after_test:
  # Publish the coverage. The deps are not listed in the requirements file because they are only useful in the CI.
  - sh: "if ((coverage)); then
             pip install pyyaml coveralls;
             coveralls;
         fi"
