environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"

# NumPy is not yet compatible with Python 3.8; see https://github.com/cython/cython/issues/2938
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      PYTHON: "3.8"

stack: python %PYTHON%

build: off

install:
  - git submodule update --init --recursive
  - pip install pyyaml coveralls  # Removed from requirements.txt because it's only useful on the CI.

  # GNU/Linux build config
  - sh: 'export extras_pkg="linux-*-extra-$(uname -r)"'
  - sh: 'echo $extras_pkg'
  - sh: 'sudo apt-get install -y $extras_pkg graphviz nmap'

  # Windows build config
  - cmd: 'SET PATH=%PYTHON%;%PATH%'
  - cmd: 'SET PATH=C:\\Python37-x64\\Scripts;%PATH%'

test_script:
  - sh: "./test.sh"
  - sh: "echo 'TODO: run SonarQube'"

# Don't push coverage metrics because it's done from Travis CI. No need to do it twice.
#after_test:
#  - coveralls
